### ISSUE TITLE
Death Saves

### ISSUE THREAD

**Issue by discuit** [evilgeniusgaming/everyday-heroes#204]
Am I blind or is there no place to track these on the sheet? Thanks!

**Comment by arbron** [comment]
It only appears when you drop to 0 hp:

<img width="392" alt="Screenshot 2023-10-17 at 16 50 49" src="https://github.com/evilgeniusgaming/everyday-heroes/assets/19979839/c0f021fa-f2bb-4996-b92f-95d835e78842">

Then you can just click where it says "Death Saves" and it will roll and keep track of the saves for you.
