### ISSUE TITLE
Damage from weapon attacks is untyped

### ISSUE THREAD

**Issue by Wemo99** [evilgeniusgaming/everyday-heroes#52]
Rolling damage in the chat window is untyped for base damage. 

e.g. Demon attack is 1d8 slashing + 3 + 1d10 fire.

However in the chat window this is shown ad 1d8 +3 + 1d10[fire]

Hooking into the damage Terms reveals:
_(Note: The type is shown as undefined but should be slashing)_

module.js:275 .terms.0.isIntermediate : false
**module.js:275 .terms.0.options.flavor : undefined**
module.js:275 .terms.0.options.baseNumber : 1
module.js:275 .terms.0._evaluated : true
module.js:275 .terms.0.number : 1
module.js:275 .terms.0.faces : 8
module.js:275 .terms.0.results.0.result : 7
module.js:275 .terms.0.results.0.active : true
module.js:275 .terms.1.isIntermediate : false
module.js:275 .terms.1._evaluated : true
module.js:275 .terms.1.operator : +
module.js:275 .terms.2.isIntermediate : false
**module.js:275 .terms.2.options.flavor : undefined**
module.js:275 .terms.2._evaluated : true
module.js:275 .terms.2.number : 3
module.js:275 .terms.3.isIntermediate : false
module.js:275 .terms.3._evaluated : true
module.js:275 .terms.3.operator : +
module.js:275 .terms.4.isIntermediate : false
**module.js:275 .terms.4.options.flavor : fire**
module.js:275 .terms.4.options.baseNumber : 1
module.js:275 .terms.4._evaluated : true
module.js:275 .terms.4.number : 1
module.js:275 .terms.4.faces : 10
module.js:275 .terms.4.results.0.result : 7
module.js:275 .terms.4.results.0.active : true

**Comment by arbron** [comment]
Multiple damage groups are better handled now, so you won't need to use roll flavor to communicate damage types. Instead you should check `options.type` on each roll itself which contains the damage type (and `options.pv` which contains its penetration value, if applicable). This only applies to damage rolled through the standard process so far, not inline rolls or manual rolls.
