### ISSUE TITLE
Add clothing as item type similar to gear

### ISSUE THREAD

**Issue by arbron** [evilgeniusgaming/everyday-heroes#93]

**Comment by kaleemullah786** [comment]
hey, can you provide more details on this

**Comment by arbron** [comment]
The pre-gen heroes list Clothes in a separate section from Gear, and NPCs also often list it among their equipment. This would just give a way to distinguish the two types so they can be stuck on sheets more clearly.

**Comment by kaleemullah786** [comment]
how to set up on local machine

**Comment by arbron** [comment]
For just playing in general, or for developing the system? For playing, here is the installation guide: https://github.com/evilgeniusgaming/everyday-heroes/wiki/Installation. For development I don't have a contribution guide set up yet, but unless you are contributing to the compendium packs all you need to do is clone the GitHub repo.
